### ISSUE TITLE
issue with pip and antlr

### ISSUE THREAD

**Issue by dadaista** [nemonik/Intellect#15]
under Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] in Win8.1
I get this when try to  pip install Intellect

Could not find a version that satisfies the requirement antlr-python-runtime>=
3.1.3 (from intellect) (from versions: )

**Comment by tuxos** [comment]
It can be installed by using a different package index
```
pip install --index-url=https://pypi.python.org/pypi antlr_python_runtime
```

**Comment by FMLS** [comment]
thx to slitayem, I don't know why I have to do this, and what it is antlr_python_runtime

**Comment by ldmax** [comment]
> It can be installed by using a different package index
> 
> ```
> pip install --index-url=https://pypi.python.org/pypi antlr_python_runtime
> ```

Succeeded by
```
pip install --index-url=https://pypi.python.org/project antlr_python_runtime
```
